# Generated by Django 5.0.6 on 2026-08-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product_alias', 'Alias de produto'), ('preference', 'Preferência')], max_length=32)),
                ('product_hint', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('preference_key', models.CharField(blank=True, max_length=64)),
                ('preference_value', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('received', 'Recebido'), ('parsing', 'Interpretando'), ('memory_loaded', 'Memória carregada'), ('validating', 'Validando'), ('waiting_customer', 'Aguardando cliente'), ('ready_for_confirmation', 'Pronto para confirmação'), ('customer_confirmed', 'Confirmado pelo cliente'), ('pending_approval', 'Aguardando aprovação'), ('sending_to_erp', 'Enviando ao ERP'), ('sent_to_erp', 'Enviado ao ERP'), ('erp_execution_failed', 'Falha na execução no ERP')], default='received', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.conversation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Cliente'), ('system', 'Sistema')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('text', 'Texto'), ('voice', 'Voz')], default='text', max_length=16)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='messages/audio/')),
                ('transcription', models.TextField(blank=True)),
                ('transcription_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('needs_clarification', 'Precisa de esclarecimento'), ('validated', 'Validado')], default='draft', max_length=32)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('clarification_question', models.TextField(blank=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by_agent', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.order')),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('order', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=255)),
                ('product_hint', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('order_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.orderversion')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.orderversion'),
        ),
        migrations.CreateModel(
            name='OperatorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('order_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_approval', to='core.orderversion')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending_review', 'Aguardando revisão'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending_review', max_length=32)),
                ('evidence', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_proposals', to='core.customer')),
                ('source_order_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_proposals', to='core.orderversion')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.message')),
                ('order_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_confirmation', to='core.orderversion')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('order_intake', 'Order Intake'), ('memory', 'Memory'), ('validation', 'Validation'), ('erp_execution', 'ERP Execution')], max_length=32)),
                ('previous_state', models.CharField(blank=True, max_length=32)),
                ('next_state', models.CharField(blank=True, max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.order')),
                ('order_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='core.orderversion')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.organization'),
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=64)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='core.agentrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
