# Generated by Django 5.0.6 on 2026-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderversion',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
